namespace Smart.Mapper.Generator;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

using Smart.Mapper.Generator.Helpers;
using Smart.Mapper.Generator.Models;

using SourceGenerateHelper;

internal static class MapperSourceBuilder
{
    internal static readonly string[] ReflectionPatterns =
    [
        "Activator.",
        "Type.GetType",
        "Assembly.Load",
        "MethodInfo",
        "PropertyInfo",
        "FieldInfo",
        "RuntimeHelpers.GetUninitializedObject",
        "MakeGenericType",
        "MakeGenericMethod"
    ];

    // Names the generated code declares start with __, which SMP0004 keeps out of mapper parameter
    // names, so they cannot collide with a parameter.
    private const string DestinationVariableName = "__d";
    private const string ExpressionFunctionPrefix = "__expression";

    internal static void BuildSource(SourceBuilder builder, EquatableArray<MapperMethodModel> methods)
    {
        var ns = methods[0].Namespace;
        var className = methods[0].ClassName;
        var isValueType = methods[0].IsValueType;

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(ns))
        {
            builder.Namespace(ns);
            builder.NewLine();
        }

        builder
            .Indent()
            .Append("partial ")
            .Append(isValueType ? "struct " : "class ")
            .Append(className)
            .NewLine();
        builder.BeginScope();

        var usedCultures = new HashSet<string>(StringComparer.Ordinal);
        foreach (var method in methods)
        {
            foreach (var mapping in method.PropertyMappings)
            {
                if (!String.IsNullOrEmpty(mapping.EffectiveCulture))
                {
                    usedCultures.Add(mapping.EffectiveCulture!);
                }
            }
        }

        if (usedCultures.Count > 0)
        {
            foreach (var culture in usedCultures.OrderBy(static c => c, StringComparer.Ordinal))
            {
                var fieldName = GetCultureFieldName(culture);
                builder.Indent()
                       .Append("private static readonly global::System.Globalization.CultureInfo ")
                       .Append(fieldName)
                       .Append(" = global::System.Globalization.CultureInfo.GetCultureInfo(\"")
                       .Append(culture)
                       .Append("\");")
                       .NewLine();
            }
            builder.NewLine();
        }

        var first = true;
        foreach (var method in methods)
        {
            if (first)
            {
                first = false;
            }
            else
            {
                builder.NewLine();
            }

            BuildMethod(builder, method);
        }

        builder.EndScope();
    }

    internal static string GetCultureFieldName(string cultureName) =>
        "__culture_" + cultureName.Replace('-', '_').Replace('.', '_');

    // Emits the parameter list with the modifiers and nullable annotations of the defining declaration,
    // which the implementation of a partial method has to repeat: this for extension mappers, and the
    // others (in, ref readonly, ref, scoped, params) as declared. The local functions computing
    // [MapExpression] values take the same list without this, which a local function cannot have, and
    // take a nullable source or destination as not null, as the method has checked it before the calls.
    private static void AppendParameters(SourceBuilder builder, MapperMethodModel method, bool forImplementation)
    {
        if (forImplementation && method.IsExtensionMethod)
        {
            builder.Append("this ");
        }

        AppendParameter(
            builder,
            method.SourceParameterModifiers,
            forImplementation ? method.SourceDeclaredTypeName : method.SourceNonNullableTypeName,
            method.SourceParameterName);

        if (!method.ReturnsDestination)
        {
            builder.Append(", ");
            AppendParameter(
                builder,
                method.DestinationParameterModifiers,
                forImplementation ? method.DestinationDeclaredTypeName : method.DestinationNonNullableTypeName,
                method.DestinationParameterName!);
        }

        foreach (var customParam in method.CustomParameters)
        {
            builder.Append(", ");
            AppendParameter(builder, customParam.Modifiers, customParam.DeclaredTypeName, customParam.Name);
        }
    }

    private static void AppendParameter(SourceBuilder builder, string modifiers, string typeName, string name)
    {
        if (modifiers.Length > 0)
        {
            builder.Append(modifiers).Append(" ");
        }

        builder.Append(typeName).Append(" ").Append(name);
    }

    // How a variable is passed to a parameter taking it with the given modifier: with ref for ref, and
    // with in for in and ref readonly (a ref readonly argument without it warns, CS9192). It serves the
    // local functions of [MapExpression], which take each mapper parameter with its own modifier, and the
    // methods the generated code calls, which the model matched only when their modifiers could take
    // the arguments.
    private static string GetArgumentModifier(RefKind refKind) => refKind switch
    {
        RefKind.Ref => "ref ",
        RefKind.In or RefKind.RefReadOnlyParameter => "in ",
        _ => string.Empty
    };

    // The modifier for passing a variable (a mapper parameter, __d, an element the loop reads, or the
    // instance created for an element mapper) as the argument at index of a called method. The property
    // value a converter, condition or nested mapper takes first is never passed through here: only by
    // value or in is allowed for it, and a value goes to in without a modifier.
    private static string GetCallArgumentModifier(EquatableArray<RefKind> parameterRefKinds, int index) =>
        index < parameterRefKinds.Count ? GetArgumentModifier(parameterRefKinds[index]) : string.Empty;

    internal static void BuildMethod(SourceBuilder builder, MapperMethodModel method)
    {
        // Mappers that emit collection loops have large bodies; forcing them into callers bloats
        // code for no gain, so AggressiveInlining is applied only to loop-free mappers.
        // (The helper path is a single converter call and stays inlinable.)
        var emitsLoop = method.MapCollectionMappings.Any(mc => mc.InPlace || !mc.UseHelperPath);
        if (!emitsLoop)
        {
            builder.Indent()
                   .Append("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]")
                   .NewLine();
        }

        builder.Indent().Append(method.MethodAccessibility.ToText()).Append(" static partial ");
        builder.Append(method.ReturnsDestination ? method.DestinationDeclaredTypeName : "void").Append(" ");
        builder.Append(method.MethodName).Append("(");
        AppendParameters(builder, method, forImplementation: true);
        builder.Append(")").NewLine();

        builder.BeginScope();

        AppendNullParameterCheck(builder, method);

        var destVarName = method.ReturnsDestination ? DestinationVariableName : method.DestinationParameterName!;

        if (method.ReturnsDestination)
        {
            if (method.UseConstructorMapping)
            {
                var initOnlyMappings = method.PropertyMappings
                    .Where(pm => (pm.IsTargetInitOnly || pm.IsTargetRequired) && !pm.IsConstructorParameter)
                    .ToList();

                // Explicit feature mappings (constant/expression/using/from) that target init-only or
                // required members must be assigned in the object initializer; the post-construction
                // loops below skip them.
                var featureInitEntries = new List<(int Order, int DefinitionOrder, string Target, string Value)>();
                foreach (var constant in method.ConstantMappings.Where(static c => c.IsTargetInitOnly || c.IsTargetRequired))
                {
                    featureInitEntries.Add((constant.Order, constant.DefinitionOrder, constant.TargetName, constant.Value ?? "null"));
                }
                for (var i = 0; i < method.ExpressionMappings.Count; i++)
                {
                    var expression = method.ExpressionMappings[i];
                    if (expression.IsTargetInitOnly || expression.IsTargetRequired)
                    {
                        featureInitEntries.Add((expression.Order, expression.DefinitionOrder, expression.TargetName, BuildExpressionValue(method, i)));
                    }
                }
                foreach (var mapUsing in method.MapUsingMappings.Where(static mu => mu.IsTargetInitOnly || mu.IsTargetRequired))
                {
                    featureInitEntries.Add((mapUsing.Order, mapUsing.DefinitionOrder, mapUsing.TargetName, BuildMapUsingCall(mapUsing, method)));
                }
                foreach (var mapFrom in method.MapFromMappings.Where(static mf => mf.IsTargetInitOnly || mf.IsTargetRequired))
                {
                    var invoke = mapFrom.IsMethodCall ? "()" : string.Empty;
                    featureInitEntries.Add((mapFrom.Order, mapFrom.DefinitionOrder, mapFrom.TargetName, $"{method.SourceParameterName}.{mapFrom.Member}{invoke}"));
                }

                var ctorParameters = method.ConstructorParameters;
                builder.Indent().Append("var ").Append(destVarName).Append(" = new ").Append(method.DestinationTypeName).Append("(");
                for (var i = 0; i < ctorParameters.Count; i++)
                {
                    if (i > 0)
                    {
                        builder.Append(", ");
                    }

                    // BuildConstructorParameterMappings guarantees a mapping exists for every
                    // argument; First is deliberate so a broken invariant fails the build loudly
                    // instead of emitting an empty argument.
                    var ctorMapping = method.PropertyMappings.First(pm => pm.TargetPath == ctorParameters[i].TargetPath);
                    AppendPropertyValue(builder, ctorMapping, method.SourceParameterName, method, nullChecked: false);
                }
                builder.Append(")");

                if ((initOnlyMappings.Count > 0) || (featureInitEntries.Count > 0))
                {
                    builder.NewLine();
                    builder.Indent().Append("{").NewLine();
                    builder.IndentLevel++;
                    foreach (var pm in initOnlyMappings)
                    {
                        builder.Indent().Append(pm.TargetPath).Append(" = ");
                        AppendPropertyValue(builder, pm, method.SourceParameterName, method, nullChecked: false);
                        builder.Append(",").NewLine();
                    }
                    foreach (var (_, _, target, value) in featureInitEntries.OrderBy(static x => x.Order).ThenBy(static x => x.DefinitionOrder))
                    {
                        builder.Indent().Append(target).Append(" = ").Append(value).Append(",").NewLine();
                    }
                    builder.IndentLevel--;
                    builder.Indent().Append("}");
                }

                builder.Append(";").NewLine();
            }
            else
            {
                builder.Indent().Append("var ").Append(destVarName).Append(" = new ").Append(method.DestinationTypeName).Append("();").NewLine();
            }
        }

        if (!String.IsNullOrEmpty(method.BeforeMapMethod))
        {
            AppendCallbackCall(builder, method, method.BeforeMapMethod!, method.BeforeMapParameterRefKinds, method.BeforeMapAcceptsCustomParameters, destVarName);
        }

        var nestedPathsToInstantiate = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var mapping in method.PropertyMappings)
        {
            if (mapping.SourcePathSegments.Any(s => s.IsNullable))
            {
                continue;
            }

            foreach (var segment in mapping.TargetPathSegments)
            {
                if (!nestedPathsToInstantiate.ContainsKey(segment.Path))
                {
                    nestedPathsToInstantiate[segment.Path] = segment.TypeName;
                }
            }
        }

        foreach (var kvp in nestedPathsToInstantiate.OrderBy(x => x.Key.Count(c => c == '.')))
        {
            builder.Indent();
            builder.Append(destVarName).Append(".").Append(kvp.Key).Append(" ??= new ").Append(kvp.Value).Append("();").NewLine();
        }

        var effectiveMappings = method.UseConstructorMapping
            ? method.PropertyMappings.Where(m => !m.IsTargetInitOnly && !m.IsTargetRequired && !m.IsConstructorParameter).ToList()
            : method.PropertyMappings.ToList();
        var sortedMappings = effectiveMappings.OrderBy(m => m.Order).ThenBy(m => m.DefinitionOrder).ToList();
        var mappingsWithoutNullCheck = sortedMappings.Where(m => !m.RequiresNullCheck()).ToList();
        var mappingsWithNullCheck = sortedMappings.Where(m => m.RequiresNullCheck()).ToList();

        foreach (var mapping in mappingsWithoutNullCheck)
        {
            BuildPropertyAssignment(builder, mapping, method.SourceParameterName, destVarName, method);
        }

        var groupedByNullCheck = mappingsWithNullCheck
            .GroupBy(m => GetNullCheckCondition(m, method.SourceParameterName))
            .Where(g => !String.IsNullOrEmpty(g.Key));

        foreach (var group in groupedByNullCheck)
        {
            builder.Indent().Append("if (").Append(group.Key).Append(")").NewLine();
            builder.BeginScope();

            var groupNestedPaths = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var mapping in group)
            {
                foreach (var segment in mapping.TargetPathSegments)
                {
                    if (!groupNestedPaths.ContainsKey(segment.Path))
                    {
                        groupNestedPaths[segment.Path] = segment.TypeName;
                    }
                }
            }

            foreach (var kvp in groupNestedPaths.OrderBy(x => x.Key.Count(c => c == '.')))
            {
                builder.Indent();
                builder.Append(destVarName).Append(".").Append(kvp.Key).Append(" ??= new ").Append(kvp.Value).Append("();").NewLine();
            }

            foreach (var mapping in group)
            {
                BuildPropertyAssignment(builder, mapping, method.SourceParameterName, destVarName, method, nullChecked: true);
            }

            builder.EndScope();
        }

        // Feature mappings already emitted in the object initializer are skipped here.
        bool EmittedInInitializer(bool isTargetInitOnly, bool isTargetRequired) =>
            method.UseConstructorMapping && (isTargetInitOnly || isTargetRequired);

        foreach (var constant in method.ConstantMappings.OrderBy(c => c.Order).ThenBy(c => c.DefinitionOrder))
        {
            if (EmittedInInitializer(constant.IsTargetInitOnly, constant.IsTargetRequired))
            {
                continue;
            }

            builder.Indent();
            builder.Append(destVarName).Append(".").Append(constant.TargetName).Append(" = ");
            builder.Append(constant.Value ?? "null");
            builder.Append(";").NewLine();
        }

        var orderedExpressions = method.ExpressionMappings
            .Select(static (e, index) => (Expression: e, Index: index))
            .OrderBy(static x => x.Expression.Order)
            .ThenBy(static x => x.Expression.DefinitionOrder);
        foreach (var (expression, index) in orderedExpressions)
        {
            if (EmittedInInitializer(expression.IsTargetInitOnly, expression.IsTargetRequired))
            {
                continue;
            }

            builder.Indent();
            builder.Append(destVarName).Append(".").Append(expression.TargetName).Append(" = ");
            builder.Append(BuildExpressionValue(method, index));
            builder.Append(";").NewLine();
        }

        foreach (var mapUsing in method.MapUsingMappings.OrderBy(m => m.Order).ThenBy(m => m.DefinitionOrder))
        {
            if (EmittedInInitializer(mapUsing.IsTargetInitOnly, mapUsing.IsTargetRequired))
            {
                continue;
            }

            builder.Indent();
            builder.Append(destVarName).Append(".").Append(mapUsing.TargetName).Append(" = ");
            builder.Append(BuildMapUsingCall(mapUsing, method));
            builder.Append(";").NewLine();
        }

        foreach (var mapFrom in method.MapFromMappings.OrderBy(m => m.Order).ThenBy(m => m.DefinitionOrder))
        {
            if (EmittedInInitializer(mapFrom.IsTargetInitOnly, mapFrom.IsTargetRequired))
            {
                continue;
            }

            builder.Indent();
            builder.Append(destVarName).Append(".").Append(mapFrom.TargetName).Append(" = ");
            builder.Append(method.SourceParameterName).Append(".");
            if (mapFrom.IsMethodCall)
            {
                builder.Append(mapFrom.Member).Append("()");
            }
            else
            {
                builder.Append(mapFrom.Member);
            }
            builder.Append(";").NewLine();
        }

        foreach (var mapNested in method.MapNestedMappings.OrderBy(m => m.Order).ThenBy(m => m.DefinitionOrder))
        {
            var sourceAccess = $"{method.SourceParameterName}.{mapNested.SourceName}";

            if (mapNested.MapperReturnsValue)
            {
                builder.Indent();
                builder.Append(destVarName).Append(".").Append(mapNested.TargetName).Append(" = ");
                if (mapNested.IsSourceNullable)
                {
                    builder.Append(sourceAccess).Append(" is not null ? ");
                }
                builder.Append(mapNested.Mapper).Append("(").Append(sourceAccess);
                if (mapNested.IsSourceNullable)
                {
                    builder.Append("!");
                }
                builder.Append(")");
                if (mapNested.IsSourceNullable)
                {
                    builder.Append(" : default!");
                }
                builder.Append(";").NewLine();
            }
            else
            {
                // The property value goes as is; the instance created for the mapper is a local, passed the
                // way the mapper takes it
                var nestedVarName = "__nested_" + mapNested.TargetName.Replace(".", "_");
                var instanceModifier = GetCallArgumentModifier(mapNested.MapperParameterRefKinds, 1);
                if (mapNested.IsSourceNullable)
                {
                    builder.Indent().Append("if (").Append(sourceAccess).Append(" is not null)").NewLine();
                    builder.BeginScope();
                    builder.Indent().Append("var ").Append(nestedVarName).Append(" = new ").Append(mapNested.TargetType).Append("();").NewLine();
                    builder.Indent().Append(mapNested.Mapper).Append("(").Append(sourceAccess).Append("!, ").Append(instanceModifier).Append(nestedVarName).Append(");").NewLine();
                    builder.Indent().Append(destVarName).Append(".").Append(mapNested.TargetName).Append(" = ").Append(nestedVarName).Append(";").NewLine();
                    builder.EndScope();
                    builder.Indent().Append("else").NewLine();
                    builder.BeginScope();
                    builder.Indent().Append(destVarName).Append(".").Append(mapNested.TargetName).Append(" = default!;").NewLine();
                    builder.EndScope();
                }
                else
                {
                    builder.Indent().Append("var ").Append(nestedVarName).Append(" = new ").Append(mapNested.TargetType).Append("();").NewLine();
                    builder.Indent().Append(mapNested.Mapper).Append("(").Append(sourceAccess).Append(", ").Append(instanceModifier).Append(nestedVarName).Append(");").NewLine();
                    builder.Indent().Append(destVarName).Append(".").Append(mapNested.TargetName).Append(" = ").Append(nestedVarName).Append(";").NewLine();
                }
            }
        }

        var collectionConverterTypeName = method.CollectionConverterTypeName ?? Names.QualifiedDefaultCollectionConverter;
        foreach (var mapCollection in method.MapCollectionMappings.OrderBy(m => m.Order).ThenBy(m => m.DefinitionOrder))
        {
            EmitCollectionMapping(builder, mapCollection, method, destVarName, collectionConverterTypeName);
        }

        if (!String.IsNullOrEmpty(method.AfterMapMethod))
        {
            AppendCallbackCall(builder, method, method.AfterMapMethod!, method.AfterMapParameterRefKinds, method.AfterMapAcceptsCustomParameters, destVarName);
        }

        if (method.ReturnsDestination)
        {
            builder.Indent().Append("return ").Append(destVarName).Append(";").NewLine();
        }

        EmitExpressionFunctions(builder, method);

        builder.EndScope();
    }

    // A source or destination declared nullable is read or written below. When it is null there is
    // nothing to map, so before anything happens (BeforeMap, creating the instance) a return-type mapper
    // returns default and a void mapper returns, leaving the destination as it is. Past the check the
    // compiler takes both as not null.
    private static void AppendNullParameterCheck(SourceBuilder builder, MapperMethodModel method)
    {
        if (!method.IsSourceParameterNullable && !method.IsDestinationParameterNullable)
        {
            return;
        }

        builder.Indent().Append("if (");
        if (method.IsSourceParameterNullable)
        {
            builder.Append(method.SourceParameterName).Append(" is null");
        }

        if (method.IsDestinationParameterNullable)
        {
            builder.Append(method.IsSourceParameterNullable ? " || " : string.Empty).Append(method.DestinationParameterName!).Append(" is null");
        }

        builder.Append(")").NewLine();
        builder.BeginScope();
        if (method.ReturnsDestination)
        {
            builder.Indent().Append("return ").Append(method.DefaultReturnValue).Append(";").NewLine();
        }
        else
        {
            builder.Indent().Append("return;").NewLine();
        }
        builder.EndScope();
    }

    // BeforeMap / AfterMap: the source, the destination and the custom parameters, each passed the way
    // the callback's parameter takes it.
    private static void AppendCallbackCall(
        SourceBuilder builder,
        MapperMethodModel method,
        string callback,
        EquatableArray<RefKind> parameterRefKinds,
        bool acceptsCustomParameters,
        string destVarName)
    {
        builder.Indent().Append(callback).Append("(")
            .Append(GetCallArgumentModifier(parameterRefKinds, 0)).Append(method.SourceParameterName).Append(", ")
            .Append(GetCallArgumentModifier(parameterRefKinds, 1)).Append(destVarName);
        if (acceptsCustomParameters)
        {
            AppendCustomArguments(builder, method, parameterRefKinds, 2);
        }
        builder.Append(");").NewLine();
    }

    private static string BuildMapUsingCall(MapUsingModel mapUsing, MapperMethodModel method)
    {
        var call = new StringBuilder(mapUsing.Method);
        call.Append('(').Append(GetCallArgumentModifier(mapUsing.ParameterRefKinds, 0)).Append(method.SourceParameterName);
        if (mapUsing.AcceptsCustomParameters)
        {
            for (var i = 0; i < method.CustomParameters.Count; i++)
            {
                call.Append(", ").Append(GetCallArgumentModifier(mapUsing.ParameterRefKinds, i + 1)).Append(method.CustomParameters[i].Name);
            }
        }
        return call.Append(')').ToString();
    }

    // The custom parameters as the arguments following the first ones of a called method.
    private static void AppendCustomArguments(SourceBuilder builder, MapperMethodModel method, EquatableArray<RefKind> parameterRefKinds, int firstIndex)
    {
        for (var i = 0; i < method.CustomParameters.Count; i++)
        {
            builder.Append(", ").Append(GetCallArgumentModifier(parameterRefKinds, firstIndex + i)).Append(method.CustomParameters[i].Name);
        }
    }

    private static string GetExpressionFunctionName(int index) =>
        ExpressionFunctionPrefix + index.ToString(CultureInfo.InvariantCulture);

    // The value assigned for the [MapExpression] at the given index: a call to its local function (see
    // EmitExpressionFunctions). An unresolved target gives no type to declare that function with, so its
    // expression stays inline and the compiler reports the missing member there, as it did before.
    private static string BuildExpressionValue(MapperMethodModel method, int index)
    {
        var expression = method.ExpressionMappings[index];
        if (expression.TargetType is null)
        {
            return expression.Expression;
        }

        var call = new StringBuilder(GetExpressionFunctionName(index));
        call.Append('(').Append(GetArgumentModifier(method.SourceRefKind)).Append(method.SourceParameterName);
        if (!method.ReturnsDestination)
        {
            call.Append(", ").Append(GetArgumentModifier(method.DestinationRefKind)).Append(method.DestinationParameterName);
        }

        foreach (var customParam in method.CustomParameters)
        {
            call.Append(", ").Append(GetArgumentModifier(customParam.RefKind)).Append(customParam.Name);
        }

        return call.Append(')').ToString();
    }

    // Each [MapExpression] becomes a static local function at the end of the method that takes the
    // mapper's parameters under the same names. Variables the expression declares (out var, patterns)
    // stay inside that function instead of colliding in the method body, and being static, it can take
    // in parameters and ref structs, which a capturing one could not. It returns the target member's
    // type, so the expression converts to the target as it would in a direct assignment.
    internal static void EmitExpressionFunctions(SourceBuilder builder, MapperMethodModel method)
    {
        var separated = false;
        var annotationsDisabled = false;
        for (var i = 0; i < method.ExpressionMappings.Count; i++)
        {
            var expression = method.ExpressionMappings[i];
            if (expression.TargetType is null)
            {
                continue;
            }

            if (!separated)
            {
                builder.NewLine();
                separated = true;
            }

            // A target declared with annotations disabled has an oblivious type. Spelled with the
            // annotations of this file it would read as non-nullable, and a null result would warn where
            // the direct assignment did not.
            if (expression.IsTargetTypeOblivious != annotationsDisabled)
            {
                annotationsDisabled = expression.IsTargetTypeOblivious;
                builder.Append(annotationsDisabled ? "#nullable disable annotations" : "#nullable enable annotations").NewLine();
            }

            builder.Indent().Append("static ").Append(expression.TargetType).Append(" ").Append(GetExpressionFunctionName(i)).Append("(");
            AppendParameters(builder, method, forImplementation: false);
            builder.Append(") => ").Append(expression.Expression).Append(";").NewLine();
        }

        if (annotationsDisabled)
        {
            builder.Append("#nullable enable annotations").NewLine();
        }
    }

    internal static void EmitCollectionMapping(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        MapperMethodModel method,
        string destVarName,
        string collectionConverterTypeName)
    {
        if (mapCollection.InPlace)
        {
            EmitInPlaceCollectionMapping(builder, mapCollection, method, destVarName);
            return;
        }

        if (mapCollection.UseHelperPath)
        {
            EmitHelperCollectionMapping(builder, mapCollection, method, destVarName, collectionConverterTypeName);
            return;
        }

        EmitInlineCollectionMapping(builder, mapCollection, method, destVarName);
    }

    internal static void EmitInPlaceCollectionMapping(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        MapperMethodModel method,
        string destVarName)
    {
        var sourceAccess = $"{method.SourceParameterName}.{mapCollection.SourceName}";
        var destAccess = $"{destVarName}.{mapCollection.TargetName}";
        var fallbackType = mapCollection.InPlaceFallbackTypeName ?? $"global::System.Collections.Generic.List<{mapCollection.TargetElementType}>";

        if (mapCollection.IsSourceNullable)
        {
            builder.Indent().Append("if (").Append(sourceAccess).Append(" is not null)").NewLine();
        }

        // The iteration locals (__srcSpan, __dstColl, ...) have fixed names, so each mapping gets a block
        // of its own, as on the inline path.
        builder.BeginScope();

        // Known-count sources size the fallback instance so the first fill avoids growth
        // reallocations (List.Clear/HashSet.Clear preserve capacity on subsequent calls).
        var srcBang = mapCollection.IsSourceNullable ? "!" : string.Empty;
        var capacityArg = mapCollection.SourceShape switch
        {
            CollectionSourceShape.Array or CollectionSourceShape.ImmutableArray or
            CollectionSourceShape.ReadOnlyMemory or CollectionSourceShape.Memory => $"{sourceAccess}{srcBang}.Length",
            CollectionSourceShape.List or CollectionSourceShape.IndexedList or
            CollectionSourceShape.ReadOnlyCollection => $"{sourceAccess}{srcBang}.Count",
            _ => string.Empty
        };

        builder.Indent().Append("if (").Append(destAccess).Append(" is null)").NewLine();
        builder.BeginScope();
        builder.Indent().Append(destAccess).Append(" = new ").Append(fallbackType).Append("(").Append(capacityArg).Append(");").NewLine();
        builder.EndScope();

        // Direct member access on a concrete List<T>/HashSet<T> lets the JIT devirtualize and inline
        // Clear/Add; the ICollection<T> cast is required only for interface-typed destinations.
        var isConcreteTarget =
            mapCollection.TargetType.StartsWith("global::System.Collections.Generic.List<", StringComparison.Ordinal) ||
            mapCollection.TargetType.StartsWith("global::System.Collections.Generic.HashSet<", StringComparison.Ordinal);
        var iCollectionType = $"global::System.Collections.Generic.ICollection<{mapCollection.TargetElementType}>";
        var collectionAccess = isConcreteTarget ? destAccess : $"(({iCollectionType}){destAccess})";
        builder.Indent().Append(collectionAccess).Append(".Clear();").NewLine();

        // A pre-existing destination may be undersized; growing once up front avoids repeated
        // reallocation during Add. EnsureCapacity is not on ICollection<T>, so this is emitted
        // only for concrete List/HashSet destinations.
        if (isConcreteTarget && (capacityArg.Length > 0))
        {
            builder.Indent().Append(collectionAccess).Append(".EnsureCapacity(").Append(capacityArg).Append(");").NewLine();
        }

        EmitInPlaceSourceIteration(builder, mapCollection, sourceAccess, collectionAccess);

        builder.EndScope();
    }

    internal static void EmitInPlaceSourceIteration(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string sourceAccess,
        string collectionAccess)
    {
        var srcNullBang = mapCollection.IsSourceNullable ? "!" : string.Empty;

        switch (mapCollection.SourceShape)
        {
            case CollectionSourceShape.Array:
            {
                builder.Indent().Append("var __srcArr = ").Append(sourceAccess).Append(srcNullBang).Append(";").NewLine();
                builder.Indent().Append("var __dstColl = ").Append(collectionAccess).Append(";").NewLine();
                builder.Indent().Append("for (var __i = 0; __i < __srcArr.Length; __i++)").NewLine();
                builder.BeginScope();
                EmitInPlaceAddItem(builder, mapCollection, "__srcArr[__i]", "__dstColl");
                builder.EndScope();
                break;
            }
            case CollectionSourceShape.List:
            {
                builder.Indent().Append("var __srcSpan = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(").Append(sourceAccess).Append(srcNullBang).Append(");").NewLine();
                builder.Indent().Append("var __dstColl = ").Append(collectionAccess).Append(";").NewLine();
                builder.Indent().Append("for (var __i = 0; __i < __srcSpan.Length; __i++)").NewLine();
                builder.BeginScope();
                EmitInPlaceAddItem(builder, mapCollection, "__srcSpan[__i]", "__dstColl");
                builder.EndScope();
                break;
            }
            case CollectionSourceShape.ImmutableArray:
            {
                builder.Indent().Append("var __srcSpan = ").Append(sourceAccess).Append(".AsSpan();").NewLine();
                builder.Indent().Append("var __dstColl = ").Append(collectionAccess).Append(";").NewLine();
                builder.Indent().Append("for (var __i = 0; __i < __srcSpan.Length; __i++)").NewLine();
                builder.BeginScope();
                EmitInPlaceAddItem(builder, mapCollection, "__srcSpan[__i]", "__dstColl");
                builder.EndScope();
                break;
            }
            case CollectionSourceShape.ReadOnlyMemory:
            case CollectionSourceShape.Memory:
            {
                builder.Indent().Append("var __srcSpan = ").Append(sourceAccess).Append(srcNullBang).Append(".Span;").NewLine();
                builder.Indent().Append("var __dstColl = ").Append(collectionAccess).Append(";").NewLine();
                builder.Indent().Append("for (var __i = 0; __i < __srcSpan.Length; __i++)").NewLine();
                builder.BeginScope();
                EmitInPlaceAddItem(builder, mapCollection, "__srcSpan[__i]", "__dstColl");
                builder.EndScope();
                break;
            }
            case CollectionSourceShape.IndexedList:
            {
                builder.Indent().Append("var __srcList = ").Append(sourceAccess).Append(srcNullBang).Append(";").NewLine();
                builder.Indent().Append("var __count = __srcList.Count;").NewLine();
                builder.Indent().Append("var __dstColl = ").Append(collectionAccess).Append(";").NewLine();
                builder.Indent().Append("for (var __i = 0; __i < __count; __i++)").NewLine();
                builder.BeginScope();
                EmitInPlaceAddItem(builder, mapCollection, "__srcList[__i]", "__dstColl");
                builder.EndScope();
                break;
            }
            default:
            {
                builder.Indent().Append("var __dstColl = ").Append(collectionAccess).Append(";").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(sourceAccess).Append(srcNullBang).Append(")").NewLine();
                builder.BeginScope();
                EmitInPlaceAddItem(builder, mapCollection, "__item", "__dstColl");
                builder.EndScope();
                break;
            }
        }
    }

    internal static void EmitInPlaceAddItem(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string itemExpr,
        string dstCollExpr)
    {
        if (mapCollection.MapperReturnsValue)
        {
            builder.Indent().Append(dstCollExpr).Append(".Add(").Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append(itemExpr).Append("));").NewLine();
        }
        else
        {
            builder.Indent().Append("var __dest = new ").Append(mapCollection.TargetElementType).Append("();").NewLine();
            builder.Indent().Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append(itemExpr).Append(", ").Append(GetInstanceArgumentModifier(mapCollection)).Append("__dest);").NewLine();
            builder.Indent().Append(dstCollExpr).Append(".Add(__dest);").NewLine();
        }
    }

    // The modifier the element goes to the element mapper with. The loops read it from an array, a span or
    // a foreach variable, all variables, except for IList<T> / IReadOnlyList<T>, whose indexer returns a
    // value, which goes as is.
    private static string GetElementArgumentModifier(MapCollectionModel mapCollection) =>
        mapCollection.SourceShape == CollectionSourceShape.IndexedList ? string.Empty : GetCallArgumentModifier(mapCollection.MapperParameterRefKinds, 0);

    // The modifier the instance created for a void element mapper goes with.
    private static string GetInstanceArgumentModifier(MapCollectionModel mapCollection) =>
        GetCallArgumentModifier(mapCollection.MapperParameterRefKinds, 1);

    // The element mapper goes to the converter method as a delegate, which the model matched only when
    // the mapper takes its parameters the way the delegate does.
    internal static void EmitHelperCollectionMapping(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        MapperMethodModel method,
        string destVarName,
        string collectionConverterTypeName)
    {
        var sourceAccess = $"{method.SourceParameterName}.{mapCollection.SourceName}";
        builder.Indent();
        builder.Append(destVarName).Append(".").Append(mapCollection.TargetName).Append(" = ");
        builder.Append(collectionConverterTypeName).Append(".");

        builder.Append(mapCollection.HasCustomConverter()
            ? mapCollection.Converter!
            : mapCollection.TargetCollectionMethod);

        builder.Append("<")
               .Append(mapCollection.SourceElementType)
               .Append(", ")
               .Append(mapCollection.TargetElementType)
               .Append(">(");
        builder.Append(sourceAccess).Append(", ");
        builder.Append(mapCollection.Mapper!);
        builder.Append(")!");
        builder.Append(";").NewLine();
    }

    internal static void EmitInlineCollectionMapping(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        MapperMethodModel method,
        string destVarName)
    {
        var sourceAccess = $"{method.SourceParameterName}.{mapCollection.SourceName}";
        var destProp = $"{destVarName}.{mapCollection.TargetName}";
        var dstElem = mapCollection.TargetElementType;
        var srcNullBang = mapCollection.IsSourceNullable ? "!" : string.Empty;

        if (mapCollection.IsSourceNullable)
        {
            if (mapCollection.SourceShape == CollectionSourceShape.ImmutableArray)
            {
                builder.Indent().Append("if (").Append(sourceAccess).Append(".IsDefaultOrEmpty)").NewLine();
                builder.BeginScope();
                builder.Indent().Append(destProp).Append(" = default!;").NewLine();
                builder.EndScope();
                builder.Indent().Append("else").NewLine();
            }
            else
            {
                builder.Indent().Append("if (").Append(sourceAccess).Append(" is null)").NewLine();
                builder.BeginScope();
                builder.Indent().Append(destProp).Append(" = default!;").NewLine();
                builder.EndScope();
                builder.Indent().Append("else").NewLine();
            }
        }

        // The locals below (__src, __srcList, __count, __list, __dst, ...) have fixed names, so each
        // mapping declares them in a block of its own. Left at method scope, they would be redeclared by a
        // second mapping in the same mapper (CS0128) and clash with those of a nullable one under its else
        // (CS0136).
        builder.BeginScope();

        switch (mapCollection.SourceShape)
        {
            case CollectionSourceShape.Array:
                builder.Indent().Append("var __src = global::System.MemoryExtensions.AsSpan(").Append(sourceAccess).Append(srcNullBang).Append(");").NewLine();
                EmitInlineTargetBuild(builder, mapCollection, dstElem, destProp, "__src", "__src.Length");
                break;
            case CollectionSourceShape.List:
                builder.Indent().Append("var __src = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(").Append(sourceAccess).Append(srcNullBang).Append(");").NewLine();
                EmitInlineTargetBuild(builder, mapCollection, dstElem, destProp, "__src", "__src.Length");
                break;
            case CollectionSourceShape.ImmutableArray:
                builder.Indent().Append("var __src = ").Append(sourceAccess).Append(".AsSpan();").NewLine();
                EmitInlineTargetBuild(builder, mapCollection, dstElem, destProp, "__src", "__src.Length");
                break;
            case CollectionSourceShape.ReadOnlyMemory:
            case CollectionSourceShape.Memory:
                builder.Indent().Append("var __src = ").Append(sourceAccess).Append(srcNullBang).Append(".Span;").NewLine();
                EmitInlineTargetBuild(builder, mapCollection, dstElem, destProp, "__src", "__src.Length");
                break;
            case CollectionSourceShape.IndexedList:
                // Count is hoisted into a local so the loop condition does not re-invoke the
                // interface Count getter on every iteration.
                builder.Indent().Append("var __srcList = ").Append(sourceAccess).Append(srcNullBang).Append(";").NewLine();
                builder.Indent().Append("var __count = __srcList.Count;").NewLine();
                EmitInlineTargetBuild(builder, mapCollection, dstElem, destProp, "__srcList", "__count");
                break;
            case CollectionSourceShape.ReadOnlyCollection:
                builder.Indent().Append("var __srcColl = ").Append(sourceAccess).Append(srcNullBang).Append(";").NewLine();
                EmitInlineTargetBuildFromCollection(builder, mapCollection, dstElem, destProp, "__srcColl", "__srcColl.Count");
                break;
            default:
                EmitInlineTargetBuildFromEnumerable(builder, mapCollection, dstElem, destProp, sourceAccess + srcNullBang);
                break;
        }

        builder.EndScope();
    }

    internal static void EmitInlineTargetBuild(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string dstElem,
        string destProp,
        string srcSpanExpr,
        string lengthExpr)
    {
        switch (mapCollection.TargetShape)
        {
            case CollectionTargetShape.Array:
                builder.Indent().Append("var __arr = new ").Append(dstElem).Append("[").Append(lengthExpr).Append("];").NewLine();
                EmitIndexedLoop(builder, mapCollection, srcSpanExpr, lengthExpr, "__arr");
                builder.Indent().Append(destProp).Append(" = __arr;").NewLine();
                break;
            case CollectionTargetShape.List:
                builder.Indent().Append("var __list = new global::System.Collections.Generic.List<").Append(dstElem).Append(">(").Append(lengthExpr).Append(");").NewLine();
                builder.Indent().Append("global::System.Runtime.InteropServices.CollectionsMarshal.SetCount(__list, ").Append(lengthExpr).Append(");").NewLine();
                builder.Indent().Append("var __dst = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(__list);").NewLine();
                EmitIndexedLoop(builder, mapCollection, srcSpanExpr, lengthExpr, "__dst");
                builder.Indent().Append(destProp).Append(" = __list;").NewLine();
                break;
            case CollectionTargetShape.ImmutableArray:
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<").Append(dstElem).Append(">(").Append(lengthExpr).Append(");").NewLine();
                EmitIndexedLoopAdd(builder, mapCollection, srcSpanExpr, lengthExpr, "__ib");
                builder.Indent().Append(destProp).Append(" = __ib.MoveToImmutable();").NewLine();
                break;
            case CollectionTargetShape.ImmutableList:
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableList.CreateBuilder<").Append(dstElem).Append(">();").NewLine();
                EmitIndexedLoopAdd(builder, mapCollection, srcSpanExpr, lengthExpr, "__ib");
                builder.Indent().Append(destProp).Append(" = __ib.ToImmutable();").NewLine();
                break;
            case CollectionTargetShape.HashSet:
                builder.Indent().Append("var __set = new global::System.Collections.Generic.HashSet<").Append(dstElem).Append(">(").Append(lengthExpr).Append(");").NewLine();
                EmitIndexedLoopAdd(builder, mapCollection, srcSpanExpr, lengthExpr, "__set");
                builder.Indent().Append(destProp).Append(" = __set;").NewLine();
                break;
            case CollectionTargetShape.ImmutableHashSet:
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableHashSet.CreateBuilder<").Append(dstElem).Append(">();").NewLine();
                EmitIndexedLoopAdd(builder, mapCollection, srcSpanExpr, lengthExpr, "__ib");
                builder.Indent().Append(destProp).Append(" = __ib.ToImmutable();").NewLine();
                break;
            case CollectionTargetShape.FrozenSet:
                builder.Indent().Append("var __set = new global::System.Collections.Generic.HashSet<").Append(dstElem).Append(">(").Append(lengthExpr).Append(");").NewLine();
                EmitIndexedLoopAdd(builder, mapCollection, srcSpanExpr, lengthExpr, "__set");
                builder.Indent().Append(destProp).Append(" = global::System.Collections.Frozen.FrozenSet.ToFrozenSet(__set);").NewLine();
                break;
        }
    }

    internal static void EmitInlineTargetBuildFromCollection(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string dstElem,
        string destProp,
        string srcExpr,
        string countExpr)
    {
        switch (mapCollection.TargetShape)
        {
            case CollectionTargetShape.Array:
                builder.Indent().Append("var __arr = new ").Append(dstElem).Append("[").Append(countExpr).Append("];").NewLine();
                builder.Indent().Append("var __idx = 0;").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAssignAsArray(builder, mapCollection, "__arr", "__idx");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __arr;").NewLine();
                break;
            case CollectionTargetShape.List:
                builder.Indent().Append("var __list = new global::System.Collections.Generic.List<").Append(dstElem).Append(">(").Append(countExpr).Append(");").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddToList(builder, mapCollection, "__list");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __list;").NewLine();
                break;
            case CollectionTargetShape.ImmutableArray:
                // Presizing the builder to the known count enables MoveToImmutable, which hands the
                // internal array over without the copy that ToImmutable performs.
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<").Append(dstElem).Append(">(").Append(countExpr).Append(");").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddBuilder(builder, mapCollection, "__ib");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __ib.MoveToImmutable();").NewLine();
                break;
            case CollectionTargetShape.HashSet:
                builder.Indent().Append("var __set = new global::System.Collections.Generic.HashSet<").Append(dstElem).Append(">(").Append(countExpr).Append(");").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddSet(builder, mapCollection, "__set");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __set;").NewLine();
                break;
            case CollectionTargetShape.FrozenSet:
                builder.Indent().Append("var __set = new global::System.Collections.Generic.HashSet<").Append(dstElem).Append(">(").Append(countExpr).Append(");").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddSet(builder, mapCollection, "__set");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = global::System.Collections.Frozen.FrozenSet.ToFrozenSet(__set);").NewLine();
                break;
            default:
                EmitInlineTargetBuildFromEnumerable(builder, mapCollection, dstElem, destProp, srcExpr);
                break;
        }
    }

    internal static void EmitInlineTargetBuildFromEnumerable(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string dstElem,
        string destProp,
        string srcExpr)
    {
        switch (mapCollection.TargetShape)
        {
            case CollectionTargetShape.Array:
                builder.Indent().Append("var __list = new global::System.Collections.Generic.List<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddToList(builder, mapCollection, "__list");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __list.ToArray();").NewLine();
                break;
            case CollectionTargetShape.ImmutableArray:
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddBuilder(builder, mapCollection, "__ib");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __ib.ToImmutable();").NewLine();
                break;
            case CollectionTargetShape.ImmutableList:
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableList.CreateBuilder<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddBuilder(builder, mapCollection, "__ib");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __ib.ToImmutable();").NewLine();
                break;
            case CollectionTargetShape.HashSet:
                builder.Indent().Append("var __set = new global::System.Collections.Generic.HashSet<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddSet(builder, mapCollection, "__set");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __set;").NewLine();
                break;
            case CollectionTargetShape.ImmutableHashSet:
                builder.Indent().Append("var __ib = global::System.Collections.Immutable.ImmutableHashSet.CreateBuilder<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddBuilder(builder, mapCollection, "__ib");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __ib.ToImmutable();").NewLine();
                break;
            case CollectionTargetShape.FrozenSet:
                builder.Indent().Append("var __set = new global::System.Collections.Generic.HashSet<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddSet(builder, mapCollection, "__set");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = global::System.Collections.Frozen.FrozenSet.ToFrozenSet(__set);").NewLine();
                break;
            default:
                builder.Indent().Append("var __list = new global::System.Collections.Generic.List<").Append(dstElem).Append(">();").NewLine();
                builder.Indent().Append("foreach (var __item in ").Append(srcExpr).Append(")").NewLine();
                builder.BeginScope();
                EmitForEachAddToList(builder, mapCollection, "__list");
                builder.EndScope();
                builder.Indent().Append(destProp).Append(" = __list;").NewLine();
                break;
        }
    }

    internal static void EmitIndexedLoop(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string srcExpr,
        string countExpr,
        string dstSpanExpr)
    {
        builder.Indent().Append("for (var __i = 0; __i < ").Append(countExpr).Append("; __i++)").NewLine();
        builder.BeginScope();
        if (mapCollection.MapperReturnsValue)
        {
            builder.Indent().Append(dstSpanExpr).Append("[__i] = ").Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append(srcExpr).Append("[__i]);").NewLine();
        }
        else
        {
            builder.Indent().Append("var __dest = new ").Append(mapCollection.TargetElementType).Append("();").NewLine();
            builder.Indent().Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append(srcExpr).Append("[__i], ").Append(GetInstanceArgumentModifier(mapCollection)).Append("__dest);").NewLine();
            builder.Indent().Append(dstSpanExpr).Append("[__i] = __dest;").NewLine();
        }
        builder.EndScope();
    }

    internal static void EmitIndexedLoopAdd(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string srcExpr,
        string countExpr,
        string containerExpr)
    {
        builder.Indent().Append("for (var __i = 0; __i < ").Append(countExpr).Append("; __i++)").NewLine();
        builder.BeginScope();
        if (mapCollection.MapperReturnsValue)
        {
            builder.Indent().Append(containerExpr).Append(".Add(").Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append(srcExpr).Append("[__i]));").NewLine();
        }
        else
        {
            builder.Indent().Append("var __dest = new ").Append(mapCollection.TargetElementType).Append("();").NewLine();
            builder.Indent().Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append(srcExpr).Append("[__i], ").Append(GetInstanceArgumentModifier(mapCollection)).Append("__dest);").NewLine();
            builder.Indent().Append(containerExpr).Append(".Add(__dest);").NewLine();
        }
        builder.EndScope();
    }

    internal static void EmitForEachAssignAsArray(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string arrExpr,
        string idxExpr)
    {
        if (mapCollection.MapperReturnsValue)
        {
            builder.Indent().Append(arrExpr).Append("[").Append(idxExpr).Append("++] = ").Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append("__item);").NewLine();
        }
        else
        {
            builder.Indent().Append("var __dest = new ").Append(mapCollection.TargetElementType).Append("();").NewLine();
            builder.Indent().Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append("__item, ").Append(GetInstanceArgumentModifier(mapCollection)).Append("__dest);").NewLine();
            builder.Indent().Append(arrExpr).Append("[").Append(idxExpr).Append("++] = __dest;").NewLine();
        }
    }

    internal static void EmitForEachAddToList(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string listExpr)
    {
        if (mapCollection.MapperReturnsValue)
        {
            builder.Indent().Append(listExpr).Append(".Add(").Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append("__item));").NewLine();
        }
        else
        {
            builder.Indent().Append("var __dest = new ").Append(mapCollection.TargetElementType).Append("();").NewLine();
            builder.Indent().Append(mapCollection.Mapper!).Append("(").Append(GetElementArgumentModifier(mapCollection)).Append("__item, ").Append(GetInstanceArgumentModifier(mapCollection)).Append("__dest);").NewLine();
            builder.Indent().Append(listExpr).Append(".Add(__dest);").NewLine();
        }
    }

    internal static void EmitForEachAddBuilder(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string builderExpr)
    {
        EmitForEachAddToList(builder, mapCollection, builderExpr);
    }

    internal static void EmitForEachAddSet(
        SourceBuilder builder,
        MapCollectionModel mapCollection,
        string setExpr)
    {
        EmitForEachAddToList(builder, mapCollection, setExpr);
    }

    internal static void BuildPropertyAssignment(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, string destVarName, MapperMethodModel method, bool nullChecked = false)
    {
        if (mapping.HasCondition())
        {
            var sourceAccessor = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);
            builder.Indent().Append("if (").Append(mapping.ConditionMethod!).Append("(").Append(sourceAccessor);
            if (mapping.ConditionAcceptsCustomParameters)
            {
                AppendCustomArguments(builder, method, mapping.ConditionParameterRefKinds, 1);
            }
            builder.Append("))").NewLine();
            builder.BeginScope();
        }

        if (mapping.IsSourceNullable && !mapping.HasConverter() && !mapping.RequiresConversion &&
            (mapping.NullBehavior == NullBehaviorType.Skip))
        {
            BuildSkipAssignment(builder, mapping, sourceParamName, destVarName, nullChecked);
        }
        else if (mapping.IsSourceNullable && mapping.RequiresConversion && !mapping.HasConverter())
        {
            BuildNullableSourceConversion(builder, mapping, sourceParamName, destVarName, method, nullChecked);
        }
        else
        {
            BuildStandardAssignment(builder, mapping, sourceParamName, destVarName, method, nullChecked);
        }

        if (mapping.HasCondition())
        {
            builder.EndScope();
        }
    }

    // Emits a guarded assignment for NullBehavior.Skip when no type conversion is required:
    // a nullable source is copied only when it has a value, otherwise the destination is left as-is.
    internal static void BuildSkipAssignment(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, string destVarName, bool nullChecked)
    {
        var sourceAccessor = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);
        var isNullableValueType = mapping.SourceType.Contains("?") || mapping.SourceType.Contains("Nullable<");

        builder.Indent().Append("if (").Append(sourceAccessor).Append(" is not null)").NewLine();
        builder.BeginScope();
        builder.Indent().Append(destVarName).Append(".").Append(mapping.TargetPath).Append(" = ").Append(sourceAccessor);
        if (!mapping.IsTargetNullable)
        {
            builder.Append(isNullableValueType ? ".GetValueOrDefault()" : "!");
        }
        builder.Append(";").NewLine();
        builder.EndScope();
    }

    internal static void BuildStandardAssignment(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, string destVarName, MapperMethodModel method, bool nullChecked)
    {
        builder.Indent();
        builder.Append(destVarName).Append(".").Append(mapping.TargetPath).Append(" = ");
        AppendPropertyValue(builder, mapping, sourceParamName, method, nullChecked);
        builder.Append(";").NewLine();
    }

    // Appends the right-hand side of a mapping as a single expression: converter call, type
    // conversion, or a plain accessor with null substitution / unwrapping.
    //
    // Constructor arguments and object-initializer entries reuse this so that they go through the
    // same conversion pipeline as ordinary property assignments. They cannot use the statement-based
    // paths (BuildSkipAssignment / BuildNullableSourceConversion), which is why the value has to be
    // expressible on its own.
    internal static void AppendPropertyValue(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, MapperMethodModel method, bool nullChecked)
    {
        // Statement contexts guard nullable intermediate path segments with a grouped `if` and pass
        // nullChecked: true; expression contexts cannot, so the guard becomes a conditional here.
        // Without it a dotted source such as src.Child!.Val dereferences a null intermediate.
        if (!nullChecked && mapping.RequiresNullCheck())
        {
            builder.Append(GetNullCheckCondition(mapping, sourceParamName)).Append(" ? ");
            AppendPropertyValueCore(builder, mapping, sourceParamName, method, nullChecked: true);
            builder.Append(" : ");
            AppendNullFallback(builder, mapping);
            return;
        }

        AppendPropertyValueCore(builder, mapping, sourceParamName, method, nullChecked);
    }

    private static void AppendPropertyValueCore(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, MapperMethodModel method, bool nullChecked)
    {
        if (!mapping.HasConverter() && mapping.IsSourceNullable && mapping.RequiresConversion)
        {
            AppendNullableSourceConversionValue(builder, mapping, sourceParamName, method, nullChecked);
            return;
        }

        if (mapping.HasConverter())
        {
            var sourceAccessor = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);
            builder.Append(mapping.ConverterMethod!).Append("(").Append(sourceAccessor);

            if (mapping.ConverterAcceptsCustomParameters)
            {
                AppendCustomArguments(builder, method, mapping.ConverterParameterRefKinds, 1);
            }

            builder.Append(")");
        }
        else if (mapping.RequiresConversion)
        {
            BuildTypeConversion(builder, mapping, sourceParamName, nullChecked, method);
        }
        else
        {
            var sourceAccessor = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);
            builder.Append(sourceAccessor);

            if (mapping.HasNullValue() && mapping.IsSourceNullable)
            {
                builder.Append(" ?? ").Append(mapping.NullValue!);
            }
            else if (mapping.RequiresNullCoalescing())
            {
                // A nullable value type source assigned to a non-nullable target must be unwrapped;
                // the null-forgiving operator alone keeps the type nullable (CS0266). Nullable reference
                // types display without "?" in FullyQualifiedFormat, so they correctly keep using "!".
                if (mapping.SourceType.Contains("?") || mapping.SourceType.Contains("Nullable<"))
                {
                    builder.Append(".GetValueOrDefault()");
                }
                else
                {
                    builder.Append("!");
                }
            }
        }
    }

    // Appends a nullable source that needs converting as one expression:
    //   <source> is not null ? <converted> : <fallback>
    // The fallback follows the destination: an explicit NullValue, null for a nullable target,
    // otherwise the target type's default.
    internal static void AppendNullableSourceConversionValue(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, MapperMethodModel method, bool nullChecked)
    {
        var sourceAccessor = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);
        var isNullableValueType = mapping.SourceType.Contains("?") || mapping.SourceType.Contains("Nullable<");

        builder.Append(sourceAccessor).Append(" is not null ? ");

        if (isNullableValueType)
        {
            BuildTypeConversionWithValueAccess(builder, mapping, sourceAccessor, method);
        }
        else
        {
            BuildTypeConversion(builder, mapping, sourceParamName, nullChecked, method);
        }

        builder.Append(" : ");
        AppendNullFallback(builder, mapping);
    }

    // The value emitted when a null source leaves nothing to convert: an explicit NullValue,
    // null for a nullable target, otherwise the target type's default.
    private static void AppendNullFallback(SourceBuilder builder, PropertyMappingModel mapping)
    {
        if (mapping.HasNullValue())
        {
            builder.Append(mapping.NullValue!);
        }
        else if (mapping.IsTargetNullable)
        {
            builder.Append("null");
        }
        else
        {
            builder.Append("default!");
        }
    }

    internal static void BuildNullableSourceConversion(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, string destVarName, MapperMethodModel method, bool nullChecked)
    {
        var sourceAccessor = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);

        var isNullableValueType = mapping.SourceType.Contains("?") ||
                                   mapping.SourceType.Contains("Nullable<");

        if (mapping.NullBehavior == NullBehaviorType.Skip)
        {
            builder.Indent().Append("if (").Append(sourceAccessor).Append(" is not null)").NewLine();
            builder.BeginScope();
            builder.Indent();
            builder.Append(destVarName).Append(".").Append(mapping.TargetPath).Append(" = ");

            if (isNullableValueType)
            {
                BuildTypeConversionWithValueAccess(builder, mapping, sourceAccessor, method);
            }
            else
            {
                BuildTypeConversion(builder, mapping, sourceParamName, nullChecked, method);
            }

            builder.Append(";").NewLine();
            builder.EndScope();
        }
        else
        {
            builder.Indent();
            builder.Append(destVarName).Append(".").Append(mapping.TargetPath).Append(" = ");
            AppendNullableSourceConversionValue(builder, mapping, sourceParamName, method, nullChecked);
            builder.Append(";").NewLine();
        }
    }

    internal static void BuildTypeConversionWithValueAccess(SourceBuilder builder, PropertyMappingModel mapping, string sourceAccessor, MapperMethodModel method)
    {
        if (mapping.IsEnumMapping())
        {
            // Guarded by the surrounding `is not null` check, so GetValueOrDefault skips the
            // redundant HasValue re-check (and throw path) that .Value would perform.
            var valueAccessor = sourceAccessor + ".GetValueOrDefault()";
            // BuildEnumConversion reads only the enum-conversion members, which this mapping already
            // carries; the copy it used to take here held exactly those same values.
            BuildEnumConversion(builder, mapping, valueAccessor);
            return;
        }

        var converterTypeName = method.MapConverterTypeName ?? Names.QualifiedDefaultValueConverter;

        if (mapping.HasSpecializedConverter())
        {
            if (mapping.HasCulture())
            {
                var formatArg = DetermineFormatArg(mapping);
                builder.Append(converterTypeName)
                       .Append(".")
                       .Append(mapping.SpecializedConverterMethod!)
                       .Append("(")
                       .Append(sourceAccessor)
                       .Append(".GetValueOrDefault(), ")
                       .Append(mapping.CultureArgumentModifier)
                       .Append(GetCultureFieldName(mapping.EffectiveCulture!))
                       .Append(formatArg)
                       .Append(")");
            }
            else
            {
                builder.Append(converterTypeName)
                       .Append(".")
                       .Append(mapping.SpecializedConverterMethod!)
                       .Append("(")
                       .Append(sourceAccessor)
                       .Append(".GetValueOrDefault())");
            }
        }
        else if (mapping.HasParsableMethod())
        {
            var targetTypeForParse = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;
            var cultureArg = mapping.HasCulture()
                ? GetCultureFieldName(mapping.EffectiveCulture!)
                : "global::System.Globalization.CultureInfo.InvariantCulture";
            if (mapping.ParseMethod == ParseMethodKind.SpanParsable)
            {
                builder.Append(targetTypeForParse).Append(".Parse(global::System.MemoryExtensions.AsSpan(")
                       .Append(sourceAccessor).Append(".GetValueOrDefault()), ")
                       .Append(cultureArg).Append(")");
            }
            else
            {
                builder.Append(targetTypeForParse).Append(".Parse(")
                       .Append(sourceAccessor).Append(".GetValueOrDefault(), ")
                       .Append(cultureArg).Append(")");
            }
        }
        else if (mapping.RequiresExplicitNumericCast)
        {
            var targetTypeForCast = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;
            builder.Append("(").Append(targetTypeForCast).Append(")").Append(sourceAccessor).Append(".GetValueOrDefault()");
        }
        else if (mapping.UserDefinedConversion == UserDefinedConversionKind.Implicit)
        {
            builder.Append(sourceAccessor).Append(".GetValueOrDefault()");
        }
        else if (mapping.HasUserDefinedExplicit())
        {
            var targetTypeForCast = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;
            builder.Append("(").Append(targetTypeForCast).Append(")").Append(sourceAccessor).Append(".GetValueOrDefault()");
        }
        else if (mapping.UseFormattable)
        {
            var formatArg = DetermineFormatArg(mapping);
            var cultureArg = mapping.HasCulture()
                ? GetCultureFieldName(mapping.EffectiveCulture!)
                : "global::System.Globalization.CultureInfo.InvariantCulture";
            var formatStr = formatArg.Length > 2 ? formatArg.Substring(2) : "null";
            builder.Append(sourceAccessor).Append(".GetValueOrDefault().ToString(").Append(formatStr).Append(", ").Append(cultureArg).Append(")");
        }
        else
        {
            var converterMethodName = method.MapConverterMethodName;
            var sourceTypeForConversion = !String.IsNullOrEmpty(mapping.SourceUnderlyingType) ? mapping.SourceUnderlyingType : mapping.SourceType;
            var targetTypeForConversion = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;

            builder.Append(converterTypeName)
                   .Append(".").Append(converterMethodName).Append("<")
                   .Append(sourceTypeForConversion)
                   .Append(", ")
                   .Append(targetTypeForConversion)
                   .Append(">(")
                   .Append(sourceAccessor)
                   .Append(".GetValueOrDefault())");
        }
    }

    internal static string GetNullCheckCondition(PropertyMappingModel mapping, string sourceParamName)
    {
        var conditions = new List<string>();

        var sourceSegmentsArr = mapping.SourcePathSegments;
        if (sourceSegmentsArr.Count > 0)
        {
            var pathBuilder = new StringBuilder();
            pathBuilder.Append(sourceParamName);

            foreach (var segment in sourceSegmentsArr)
            {
                pathBuilder.Append('.').Append(segment.Path.Split('.').Last());
                if (segment.IsNullable)
                {
                    conditions.Add($"{pathBuilder} is not null");
                }
            }
        }

        return String.Join(" && ", conditions);
    }

    internal static string BuildSourceAccessor(string sourcePath, string sourceParamName, bool nullChecked = false)
    {
        if (!sourcePath.Contains('.'))
        {
            return $"{sourceParamName}.{sourcePath}";
        }

        var parts = sourcePath.Split('.');
        var result = new StringBuilder();
        result.Append(sourceParamName);

        for (var i = 0; i < parts.Length; i++)
        {
            result.Append('.');
            result.Append(parts[i]);

            if ((i < parts.Length - 1) && (!nullChecked))
            {
                result.Append('!');
            }
        }

        return result.ToString();
    }

    internal static void BuildTypeConversion(SourceBuilder builder, PropertyMappingModel mapping, string sourceParamName, bool nullChecked, MapperMethodModel method)
    {
        var sourceExpr = BuildSourceAccessor(mapping.SourcePath, sourceParamName, nullChecked);

        if (mapping.IsEnumMapping())
        {
            BuildEnumConversion(builder, mapping, sourceExpr);
            return;
        }

        var converterTypeName = method.MapConverterTypeName ?? Names.QualifiedDefaultValueConverter;

        if (mapping.HasSpecializedConverter())
        {
            if (mapping.HasCulture())
            {
                var formatArg = DetermineFormatArg(mapping);
                builder.Append(converterTypeName)
                       .Append(".")
                       .Append(mapping.SpecializedConverterMethod!)
                       .Append("(")
                       .Append(sourceExpr)
                       .Append(", ")
                       .Append(mapping.CultureArgumentModifier)
                       .Append(GetCultureFieldName(mapping.EffectiveCulture!))
                       .Append(formatArg)
                       .Append(")");
            }
            else
            {
                builder.Append(converterTypeName)
                       .Append(".")
                       .Append(mapping.SpecializedConverterMethod!)
                       .Append("(")
                       .Append(sourceExpr)
                       .Append(")");
            }
        }
        else if (mapping.HasParsableMethod())
        {
            var targetTypeForParse = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;
            var cultureArg = mapping.HasCulture()
                ? GetCultureFieldName(mapping.EffectiveCulture!)
                : "global::System.Globalization.CultureInfo.InvariantCulture";
            if (mapping.ParseMethod == ParseMethodKind.SpanParsable)
            {
                builder.Append(targetTypeForParse).Append(".Parse(global::System.MemoryExtensions.AsSpan(")
                       .Append(sourceExpr).Append("), ")
                       .Append(cultureArg).Append(")");
            }
            else
            {
                builder.Append(targetTypeForParse).Append(".Parse(")
                       .Append(sourceExpr).Append(", ")
                       .Append(cultureArg).Append(")");
            }
        }
        else if (mapping.RequiresExplicitNumericCast)
        {
            var targetTypeForCast = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;
            builder.Append("(").Append(targetTypeForCast).Append(")").Append(sourceExpr);
        }
        else if (mapping.HasUserDefinedExplicit())
        {
            var targetTypeForCast = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;
            builder.Append("(").Append(targetTypeForCast).Append(")").Append(sourceExpr);
        }
        else if (mapping.UseFormattable)
        {
            var formatArg = DetermineFormatArg(mapping);
            var cultureArg = mapping.HasCulture()
                ? GetCultureFieldName(mapping.EffectiveCulture!)
                : "global::System.Globalization.CultureInfo.InvariantCulture";
            var formatStr = formatArg.Length > 2 ? formatArg.Substring(2) : "null";
            builder.Append(sourceExpr).Append(".ToString(").Append(formatStr).Append(", ").Append(cultureArg).Append(")");
        }
        else
        {
            var converterMethodName = method.MapConverterMethodName;
            var sourceTypeForConversion = !String.IsNullOrEmpty(mapping.SourceUnderlyingType) ? mapping.SourceUnderlyingType : mapping.SourceType;
            var targetTypeForConversion = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;

            builder.Append(converterTypeName)
                   .Append(".").Append(converterMethodName).Append("<")
                   .Append(sourceTypeForConversion)
                   .Append(", ")
                   .Append(targetTypeForConversion)
                   .Append(">(")
                   .Append(sourceExpr)
                   .Append(")");
        }
    }

    internal static string DetermineFormatArg(PropertyMappingModel mapping)
    {
        var isDateTimeFamily = TypeNameHelper.IsDateTimeType(mapping.SourceUnderlyingType) || TypeNameHelper.IsDateTimeType(mapping.TargetUnderlyingType);
        var format = isDateTimeFamily ? mapping.EffectiveDateTimeFormat : mapping.EffectiveNumberFormat;
        return format is null ? ", null" : $", \"{format}\"";
    }

    internal static void BuildEnumConversion(SourceBuilder builder, PropertyMappingModel mapping, string sourceExpr)
    {
        var targetType = !String.IsNullOrEmpty(mapping.TargetUnderlyingType) ? mapping.TargetUnderlyingType : mapping.TargetType;

        switch (mapping.EnumMappingKind)
        {
            case EnumMappingKind.EnumToEnum:
                builder.Append(sourceExpr).Append(" switch").NewLine();
                builder.Indent().Append("{").NewLine();
                var destMembersArr = mapping.DestEnumMembers;
                foreach (var memberName in mapping.SourceEnumMembers)
                {
                    var sourceType = !String.IsNullOrEmpty(mapping.SourceUnderlyingType) ? mapping.SourceUnderlyingType : mapping.SourceType;
                    if (destMembersArr.Contains(memberName, StringComparer.Ordinal))
                    {
                        builder.Indent().Append("    ")
                               .Append(sourceType).Append(".").Append(memberName)
                               .Append(" => ")
                               .Append(targetType).Append(".").Append(memberName)
                               .Append(",").NewLine();
                    }
                }
                builder.Indent().Append("    _ => default").NewLine();
                builder.Indent().Append("}");
                break;

            case EnumMappingKind.EnumToNumeric:
                builder.Append("(").Append(targetType).Append(")").Append(sourceExpr);
                break;

            case EnumMappingKind.NumericToEnum:
                builder.Append("(").Append(targetType).Append(")").Append(sourceExpr);
                break;

            case EnumMappingKind.EnumToString:
                // Member names are known at compile time; a switch returns cached string constants
                // without the boxing/name-lookup cost of Enum.ToString. Undefined values (e.g. flags
                // combinations) fall back to ToString to preserve semantics.
                if (mapping.SourceEnumMembers.Count > 0)
                {
                    var enumSourceType = !String.IsNullOrEmpty(mapping.SourceUnderlyingType) ? mapping.SourceUnderlyingType : mapping.SourceType;
                    builder.Append(sourceExpr).Append(" switch").NewLine();
                    builder.Indent().Append("{").NewLine();
                    foreach (var memberName in mapping.SourceEnumMembers)
                    {
                        builder.Indent().Append("    ")
                               .Append(enumSourceType).Append(".").Append(memberName)
                               .Append(" => \"").Append(memberName).Append("\",").NewLine();
                    }
                    builder.Indent().Append("    _ => ").Append(sourceExpr).Append(".ToString()").NewLine();
                    builder.Indent().Append("}");
                }
                else
                {
                    builder.Append(sourceExpr).Append(".ToString()");
                }
                break;

            case EnumMappingKind.StringToEnum:
                // A string switch (length/char dispatch) avoids the Enum.Parse machinery for exact
                // member names; anything else (numeric strings, whitespace, flags lists) falls back
                // to Enum.Parse to preserve semantics.
                if (mapping.DestEnumMembers.Count > 0)
                {
                    builder.Append(sourceExpr).Append(" switch").NewLine();
                    builder.Indent().Append("{").NewLine();
                    foreach (var memberName in mapping.DestEnumMembers)
                    {
                        builder.Indent().Append("    \"").Append(memberName).Append("\" => ")
                               .Append(targetType).Append(".").Append(memberName)
                               .Append(",").NewLine();
                    }
                    builder.Indent().Append("    _ => global::System.Enum.Parse<").Append(targetType).Append(">(").Append(sourceExpr).Append(")").NewLine();
                    builder.Indent().Append("}");
                }
                else
                {
                    builder.Append("global::System.Enum.Parse<").Append(targetType).Append(">(").Append(sourceExpr).Append(")");
                }
                break;
        }
    }
}
